"""
Django settings for NBA project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ihfyfkb6wnpx%rh0slyiq$d)xb$4gqvyurh@%gn_%mz&(kd3h6'

# SECURITY WARNING: don't run with debug turned on in production!
# 在实际展示中记得关掉，设为False后就是正常的404页面，而不是debug详细信息，防止被攻击
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
# 注册应用 我们使用了simpleui以及自己书写的backend应用
INSTALLED_APPS = [
    'simpleui',
    'admin_honeypot',
    'backend.apps.BackendConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'NBA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NBA.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'final_pj',
        'USER':'root',
        'PASSWORD':'hjkhnm123',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# simpleui
SIMPLEUI_HOME_INFO = False

SIMPLEUI_LOGO = 'https://avatars.githubusercontent.com/u/78390095?v=4'

SIMPLEUI_DEFAULT_THEME = 'element.css'

SIMPLEUI_CONFIG = {
    'system_keep': False, # 关闭系统菜单
    'menu_display': ['任务管理', '权限认证','风险管理'],
    'dynamic': True,    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'menus': [{
        'app': 'backend',
        'name': '任务管理',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '教练信息管理',
            'icon': 'fa fa-chalkboard-teacher',
            'url': 'backend/coach/'
        },{
            'name': '队伍信息管理',
            'icon': 'fas fa-users',
            'url': 'backend/team/'
        },{
            'name': '球员信息管理',
            'icon': 'fa fa-user',
            'url': 'backend/player/',
        },{
            'name': '赛事信息管理',
            'icon': 'fas fa-clipboard-list',
            'url': 'backend/game/'
        },{
            'name': '技术统计管理',
            'icon': 'fas fa-database',
            'url': 'backend/playergame/'
        }]
    },{
        'app': 'auth',
        'name': '权限认证',
        'icon': 'fas fa-exclamation-triangle',
        'models': [{
            'name': '用户管理',
            'icon': 'fa fa-user-cog',
            'url': 'auth/user/'
        },{
            'name': '用户组管理',
            'icon': 'fas fa-users-cog',
            'url': 'auth/group/'
        }]
    },{
        'app': 'admin_honeypot',
        'name': '风险管理',
        'icon': 'fas fa-assistive-listening-systems',
        'models': [{
            'name': '潜在攻击',
            'icon': 'fas fa-unlink',
            'url': 'admin_honeypot/loginattempt/'
        }]
    }]
}



# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# 国际化
LANGUAGE_CODE = 'zh-hans'

# 时区控制，实现多地不冲突
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
